spring:
  application:
    name: api_aerolinea
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aerolinea_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080
